/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-11-20

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include "control.h"
#include "stdio.h"
#include "time.h"
#include "encoder.h"
#include "IMU.h"
#include "SPI.h"
#include "motor.h"
#include "logger.h"
#include "EKF.h"
#include "ADC.h"

//Includes for Tilen's USB library
#include "defines.h"
#include "tm_stm32f4_usb_vcp.h"
//#include "tm_stm32f4_disco.h"

//Temp definitions
#define GRAVITY					9.8066
#define PI_VAL					3.1416
#define IMU_RADIUS				0.03
#define ACC_GAIN				8192
#define ACC_NOISE				0.008*GRAVITY
#define GYRO_GAIN				16.4
#define GYRO_NOISE				0.1*PI_VAL/180
#define ENCODER_GAIN			500*4/(2*PI_VAL)
#define ENCODER_START_VALUE		0x7fffffff
#define ENCODER_NOISE			(0.5/ENCODER_GAIN)*(0.5/ENCODER_GAIN)
#define SAMPLE_TIME				0.001
#define MAX_JERK				0.1
#define N						51

/* Private macro */
/* Private variables */
unsigned int count = 0;
uint16_t loopCount = 0;
float sensorValues[4];
int16_t raw_acc[3]; //xyz
int16_t raw_gyro[3]; //xyz
uint8_t raw_temp[2];
uint16_t current;
unsigned int pwm = 0;
CommsTask_TransmitPacketStruct encode;
union Data data;
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
int main(void)
{
	TIM7_INIT();
	TIM7_NVIC_Init();
	ENCODER_Init();
	uint32_t m=0;
	uint32_t n=0;
	for(m=0;m<65000;m++)
	{
		for(n=0;n<650;n++)
		{
			asm("nop");
		}
	}
	initSPI();
	PWM_Init();
	loggingInit();
	ADC_DeInit();
	initADC();
	setDutyCycle(10);

	//Initalise USB VCP
	TM_USB_VCP_Init();

	GPIO_InitTypeDef GPIO_InitDef;
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	//Pin 0
	GPIO_InitDef.GPIO_Pin = GPIO_Pin_0;
	//Mode output
	GPIO_InitDef.GPIO_Mode = GPIO_Mode_IN;
	//Output type push-pull
	GPIO_InitDef.GPIO_OType = GPIO_OType_PP;
	//With pull down resistor
	GPIO_InitDef.GPIO_PuPd = GPIO_PuPd_DOWN;
	//50MHz pin speed
	GPIO_InitDef.GPIO_Speed = GPIO_Speed_50MHz;

	//Initialize pin on GPIOA port
	GPIO_Init(GPIOA, &GPIO_InitDef);
	GPIO_WriteBit(GPIOD, GPIO_Pin_2, Bit_SET);
	/**
	 *  IMPORTANT NOTE!
	 *  The symbol VECT_TAB_SRAM needs to be defined when building the project
	 *  if code has been located to RAM and interrupts are used.
	 *  Otherwise the interrupt table located in flash will be used.
	 *  See also the <system_*.c> file and how the SystemInit() function updates
	 *  SCB->VTOR register.
	 *  E.g.  SCB->VTOR = 0x20000000;
	 */
	setDutyCycle(30);
	volatile int power1 = readSingleSPI(107);
	volatile int power2 = readSingleSPI(108);
	volatile int whoami = readSingleSPI(117);
	volatile int fifo = readSingleSPI(35);
	/* Infinite loop */
	while (1){
		loopCount++;
		count = TIM_GetCounter(TIM2);
		current = readADC();

		if (GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0)) {
			if(pwm == 50){
				pwm = 0;
			} else {
				pwm = 50;
			}
			for(m=0;m<65000;m++)
			{
				for(n=0;n<650;n++)
				{
					asm("nop");
				}
			}
			setDutyCycle(pwm);
		}

		union Raw{
			uint8_t i[14];
			int16_t j[7];
			uint16_t k[7];
		}rawData;

		uint8_t rawData2[14];

		memset(rawData.i, 0, 14);
		//Transmit data in xyz order
		/*Data in XYZ order but gyro x is at pos 0. Not sure why. TODO: Fix order*/
		readMultipleSPI(116, rawData.i, 14);
//		int x = ((readSingleSPI(114))<<8) + readSingleSPI(115);
		swap(rawData.i, 14);

//		int16_t procData[7];
//		for(int i=0; i<7; ++i){
//			procData[i] = ((rawData2[2*i])<<8) + rawData2[2*i+1];
//		}

		data.i[0] = count;
		data.a[2] = loopCount;
		data.j[3] = rawData.j[0];
		data.j[4] = rawData.j[1];
		data.j[5] = rawData.j[2];
		data.j[6] = rawData.j[3];
		data.j[7] = rawData.j[4];
		data.j[8] = rawData.j[5];
		data.a[9] = rawData.k[6];
		data.j[10] =current;

		encode = serialTerminal_packetize(data.k, 22);

		TM_USB_VCP_Send(encode.data, encode.bytes_to_tx);

		while(start()==0);
		reset();
	}
}

/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
	/* TODO, implement your code here */
	return -1;
}
